### ISSUE TITLE
Errors in examples in the README

### ISSUE THREAD

**Issue by georgpfolz** [JavaScriptDude/multisort#1]
Two statements throw errors:

### 1
```
rows_sorted = multisort(rows_dict, [
        ('grade', reverse=False),
        ('attend')
])
```

correct:
```
rows_sorted = multisort(rows_dict, [
        ('grade', False),
        ('attend')
])
```

### 2

```
rows_sorted = multisort(rows_dict, [
        mscol('grade', 'reverse'=False, clean=lambda s: None if s is None else s.upper()),
        ('attend')
])
```

- SyntaxError: expression cannot contain assignment, perhaps you meant "=="? -> remove the quotes around reverse
- NameError: name 'mscol' is not defined

**Comment by JavaScriptDude** [comment]
Funny enough, I noticed a couple of those last week while in some deep development and was planning to review. 

Thanks for going through these. I'll address ASAP.

**Comment by JavaScriptDude** [comment]
Updated docs and samples with 0.1.4. Thanks for making note of this.

FYI - I had changed the API along the way and looks like I forgot to update the docs at that time.
